// src/pages/WritePost/blogPreview.tsx
import React from "react";
import parse from "html-react-parser";

/**
 * BlogPreview component
 * Renders a live preview of the supplied HTML string using html-react-parser
 * and also displays the raw HTML content in a read‑only textarea beneath the preview.
 *
 * Props:
 *  - htmlContent: The HTML string generated by the editor (e.g. from Tiptap).
 */
interface BlogPreviewProps {
  htmlContent: string;
}

const BlogPreview: React.FC<BlogPreviewProps> = ({ htmlContent }) => {
  return (
    <div className="space-y-6">
      {/* Rendered HTML preview */}
      <div className="p-6 bg-white border border-slate-200 rounded-xl shadow-sm prose prose-sm max-w-none">
        {parse(htmlContent || "<p>Preview will appear here…</p>")}
      </div>

      {/* Raw HTML content box */}
      <div className="space-y-2">
        <label className="block text-xs font-semibold uppercase tracking-wider text-slate-600">
          HTML Content (raw)
        </label>
        <textarea
          readOnly
          value={htmlContent}
          rows={10}
          className="w-full font-mono text-xs bg-white border border-slate-200 rounded-lg p-3 resize-none focus:outline-none focus:border-orange-500 focus:ring-1 focus:ring-orange-500/20"
        />
      </div>
    </div>
  );
};

export default BlogPreview;
